/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsEnum,
  IsOptional,
  IsString,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumCitas02Estado } from "./EnumCitas02Estado";
import { Medico } from "../../medico/base/Medico";
import { Paciente } from "../../paciente/base/Paciente";
import { EnumCitas02Tipo } from "./EnumCitas02Tipo";

@ObjectType()
class Citas02 {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    enum: EnumCitas02Estado,
  })
  @IsEnum(EnumCitas02Estado)
  @IsOptional()
  @Field(() => EnumCitas02Estado, {
    nullable: true,
  })
  estado?: "Option1" | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  fechaHora!: Date | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: () => Medico,
  })
  @ValidateNested()
  @Type(() => Medico)
  @IsOptional()
  medico?: Medico | null;

  @ApiProperty({
    required: false,
    type: () => Paciente,
  })
  @ValidateNested()
  @Type(() => Paciente)
  @IsOptional()
  paciente?: Paciente | null;

  @ApiProperty({
    required: false,
    enum: EnumCitas02Tipo,
  })
  @IsEnum(EnumCitas02Tipo)
  @IsOptional()
  @Field(() => EnumCitas02Tipo, {
    nullable: true,
  })
  tipo?: "Option1" | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Citas02 as Citas02 };
