/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Citas02WhereInput } from "./Citas02WhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class Citas02ListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => Citas02WhereInput,
  })
  @ValidateNested()
  @Type(() => Citas02WhereInput)
  @IsOptional()
  @Field(() => Citas02WhereInput, {
    nullable: true,
  })
  every?: Citas02WhereInput;

  @ApiProperty({
    required: false,
    type: () => Citas02WhereInput,
  })
  @ValidateNested()
  @Type(() => Citas02WhereInput)
  @IsOptional()
  @Field(() => Citas02WhereInput, {
    nullable: true,
  })
  some?: Citas02WhereInput;

  @ApiProperty({
    required: false,
    type: () => Citas02WhereInput,
  })
  @ValidateNested()
  @Type(() => Citas02WhereInput)
  @IsOptional()
  @Field(() => Citas02WhereInput, {
    nullable: true,
  })
  none?: Citas02WhereInput;
}
export { Citas02ListRelationFilter as Citas02ListRelationFilter };
