/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Citas02WhereInput } from "./Citas02WhereInput";
import { Type } from "class-transformer";

@ArgsType()
class Citas02CountArgs {
  @ApiProperty({
    required: false,
    type: () => Citas02WhereInput,
  })
  @Field(() => Citas02WhereInput, { nullable: true })
  @Type(() => Citas02WhereInput)
  where?: Citas02WhereInput;
}

export { Citas02CountArgs as Citas02CountArgs };
