/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { Citas02Service } from "../citas02.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Citas02CreateInput } from "./Citas02CreateInput";
import { Citas02 } from "./Citas02";
import { Citas02FindManyArgs } from "./Citas02FindManyArgs";
import { Citas02WhereUniqueInput } from "./Citas02WhereUniqueInput";
import { Citas02UpdateInput } from "./Citas02UpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class Citas02ControllerBase {
  constructor(
    protected readonly service: Citas02Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Citas02 })
  @nestAccessControl.UseRoles({
    resource: "Citas02",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCitas02(
    @common.Body() data: Citas02CreateInput
  ): Promise<Citas02> {
    return await this.service.createCitas02({
      data: {
        ...data,

        medico: data.medico
          ? {
              connect: data.medico,
            }
          : undefined,

        paciente: data.paciente
          ? {
              connect: data.paciente,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        estado: true,
        fechaHora: true,
        id: true,

        medico: {
          select: {
            id: true,
          },
        },

        paciente: {
          select: {
            id: true,
          },
        },

        tipo: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Citas02] })
  @ApiNestedQuery(Citas02FindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Citas02",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async citas02s(@common.Req() request: Request): Promise<Citas02[]> {
    const args = plainToClass(Citas02FindManyArgs, request.query);
    return this.service.citas02s({
      ...args,
      select: {
        createdAt: true,
        estado: true,
        fechaHora: true,
        id: true,

        medico: {
          select: {
            id: true,
          },
        },

        paciente: {
          select: {
            id: true,
          },
        },

        tipo: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Citas02 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Citas02",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async citas02(
    @common.Param() params: Citas02WhereUniqueInput
  ): Promise<Citas02 | null> {
    const result = await this.service.citas02({
      where: params,
      select: {
        createdAt: true,
        estado: true,
        fechaHora: true,
        id: true,

        medico: {
          select: {
            id: true,
          },
        },

        paciente: {
          select: {
            id: true,
          },
        },

        tipo: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Citas02 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Citas02",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCitas02(
    @common.Param() params: Citas02WhereUniqueInput,
    @common.Body() data: Citas02UpdateInput
  ): Promise<Citas02 | null> {
    try {
      return await this.service.updateCitas02({
        where: params,
        data: {
          ...data,

          medico: data.medico
            ? {
                connect: data.medico,
              }
            : undefined,

          paciente: data.paciente
            ? {
                connect: data.paciente,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          estado: true,
          fechaHora: true,
          id: true,

          medico: {
            select: {
              id: true,
            },
          },

          paciente: {
            select: {
              id: true,
            },
          },

          tipo: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Citas02 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Citas02",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCitas02(
    @common.Param() params: Citas02WhereUniqueInput
  ): Promise<Citas02 | null> {
    try {
      return await this.service.deleteCitas02({
        where: params,
        select: {
          createdAt: true,
          estado: true,
          fechaHora: true,
          id: true,

          medico: {
            select: {
              id: true,
            },
          },

          paciente: {
            select: {
              id: true,
            },
          },

          tipo: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
