/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Citas02 } from "./Citas02";
import { Citas02CountArgs } from "./Citas02CountArgs";
import { Citas02FindManyArgs } from "./Citas02FindManyArgs";
import { Citas02FindUniqueArgs } from "./Citas02FindUniqueArgs";
import { CreateCitas02Args } from "./CreateCitas02Args";
import { UpdateCitas02Args } from "./UpdateCitas02Args";
import { DeleteCitas02Args } from "./DeleteCitas02Args";
import { Medico } from "../../medico/base/Medico";
import { Paciente } from "../../paciente/base/Paciente";
import { Citas02Service } from "../citas02.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Citas02)
export class Citas02ResolverBase {
  constructor(
    protected readonly service: Citas02Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Citas02",
    action: "read",
    possession: "any",
  })
  async _citas02sMeta(
    @graphql.Args() args: Citas02CountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Citas02])
  @nestAccessControl.UseRoles({
    resource: "Citas02",
    action: "read",
    possession: "any",
  })
  async citas02s(
    @graphql.Args() args: Citas02FindManyArgs
  ): Promise<Citas02[]> {
    return this.service.citas02s(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Citas02, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Citas02",
    action: "read",
    possession: "own",
  })
  async citas02(
    @graphql.Args() args: Citas02FindUniqueArgs
  ): Promise<Citas02 | null> {
    const result = await this.service.citas02(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Citas02)
  @nestAccessControl.UseRoles({
    resource: "Citas02",
    action: "create",
    possession: "any",
  })
  async createCitas02(
    @graphql.Args() args: CreateCitas02Args
  ): Promise<Citas02> {
    return await this.service.createCitas02({
      ...args,
      data: {
        ...args.data,

        medico: args.data.medico
          ? {
              connect: args.data.medico,
            }
          : undefined,

        paciente: args.data.paciente
          ? {
              connect: args.data.paciente,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Citas02)
  @nestAccessControl.UseRoles({
    resource: "Citas02",
    action: "update",
    possession: "any",
  })
  async updateCitas02(
    @graphql.Args() args: UpdateCitas02Args
  ): Promise<Citas02 | null> {
    try {
      return await this.service.updateCitas02({
        ...args,
        data: {
          ...args.data,

          medico: args.data.medico
            ? {
                connect: args.data.medico,
              }
            : undefined,

          paciente: args.data.paciente
            ? {
                connect: args.data.paciente,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Citas02)
  @nestAccessControl.UseRoles({
    resource: "Citas02",
    action: "delete",
    possession: "any",
  })
  async deleteCitas02(
    @graphql.Args() args: DeleteCitas02Args
  ): Promise<Citas02 | null> {
    try {
      return await this.service.deleteCitas02(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Medico, {
    nullable: true,
    name: "medico",
  })
  @nestAccessControl.UseRoles({
    resource: "Medico",
    action: "read",
    possession: "any",
  })
  async getMedico(@graphql.Parent() parent: Citas02): Promise<Medico | null> {
    const result = await this.service.getMedico(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Paciente, {
    nullable: true,
    name: "paciente",
  })
  @nestAccessControl.UseRoles({
    resource: "Paciente",
    action: "read",
    possession: "any",
  })
  async getPaciente(
    @graphql.Parent() parent: Citas02
  ): Promise<Paciente | null> {
    const result = await this.service.getPaciente(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
