/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Citas02WhereInput } from "./Citas02WhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Citas02OrderByInput } from "./Citas02OrderByInput";

@ArgsType()
class Citas02FindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Citas02WhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Citas02WhereInput, { nullable: true })
  @Type(() => Citas02WhereInput)
  where?: Citas02WhereInput;

  @ApiProperty({
    required: false,
    type: [Citas02OrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Citas02OrderByInput], { nullable: true })
  @Type(() => Citas02OrderByInput)
  orderBy?: Array<Citas02OrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Citas02FindManyArgs as Citas02FindManyArgs };
