/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Citas02 as PrismaCitas02,
  Medico as PrismaMedico,
  Paciente as PrismaPaciente,
} from "@prisma/client";

export class Citas02ServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.Citas02CountArgs, "select">): Promise<number> {
    return this.prisma.citas02.count(args);
  }

  async citas02s(args: Prisma.Citas02FindManyArgs): Promise<PrismaCitas02[]> {
    return this.prisma.citas02.findMany(args);
  }
  async citas02(
    args: Prisma.Citas02FindUniqueArgs
  ): Promise<PrismaCitas02 | null> {
    return this.prisma.citas02.findUnique(args);
  }
  async createCitas02(args: Prisma.Citas02CreateArgs): Promise<PrismaCitas02> {
    return this.prisma.citas02.create(args);
  }
  async updateCitas02(args: Prisma.Citas02UpdateArgs): Promise<PrismaCitas02> {
    return this.prisma.citas02.update(args);
  }
  async deleteCitas02(args: Prisma.Citas02DeleteArgs): Promise<PrismaCitas02> {
    return this.prisma.citas02.delete(args);
  }

  async getMedico(parentId: string): Promise<PrismaMedico | null> {
    return this.prisma.citas02
      .findUnique({
        where: { id: parentId },
      })
      .medico();
  }

  async getPaciente(parentId: string): Promise<PrismaPaciente | null> {
    return this.prisma.citas02
      .findUnique({
        where: { id: parentId },
      })
      .paciente();
  }
}
