/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumCitas02Estado } from "./EnumCitas02Estado";
import { IsEnum, IsOptional, ValidateNested } from "class-validator";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { Type } from "class-transformer";
import { StringFilter } from "../../util/StringFilter";
import { MedicoWhereUniqueInput } from "../../medico/base/MedicoWhereUniqueInput";
import { PacienteWhereUniqueInput } from "../../paciente/base/PacienteWhereUniqueInput";
import { EnumCitas02Tipo } from "./EnumCitas02Tipo";

@InputType()
class Citas02WhereInput {
  @ApiProperty({
    required: false,
    enum: EnumCitas02Estado,
  })
  @IsEnum(EnumCitas02Estado)
  @IsOptional()
  @Field(() => EnumCitas02Estado, {
    nullable: true,
  })
  estado?: "Option1";

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  fechaHora?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => MedicoWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => MedicoWhereUniqueInput)
  @IsOptional()
  @Field(() => MedicoWhereUniqueInput, {
    nullable: true,
  })
  medico?: MedicoWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => PacienteWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PacienteWhereUniqueInput)
  @IsOptional()
  @Field(() => PacienteWhereUniqueInput, {
    nullable: true,
  })
  paciente?: PacienteWhereUniqueInput;

  @ApiProperty({
    required: false,
    enum: EnumCitas02Tipo,
  })
  @IsEnum(EnumCitas02Tipo)
  @IsOptional()
  @Field(() => EnumCitas02Tipo, {
    nullable: true,
  })
  tipo?: "Option1";
}

export { Citas02WhereInput as Citas02WhereInput };
