/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumCitas02Estado } from "./EnumCitas02Estado";
import { IsEnum, IsOptional, IsDate, ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { MedicoWhereUniqueInput } from "../../medico/base/MedicoWhereUniqueInput";
import { PacienteWhereUniqueInput } from "../../paciente/base/PacienteWhereUniqueInput";
import { EnumCitas02Tipo } from "./EnumCitas02Tipo";

@InputType()
class Citas02UpdateInput {
  @ApiProperty({
    required: false,
    enum: EnumCitas02Estado,
  })
  @IsEnum(EnumCitas02Estado)
  @IsOptional()
  @Field(() => EnumCitas02Estado, {
    nullable: true,
  })
  estado?: "Option1" | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  fechaHora?: Date | null;

  @ApiProperty({
    required: false,
    type: () => MedicoWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => MedicoWhereUniqueInput)
  @IsOptional()
  @Field(() => MedicoWhereUniqueInput, {
    nullable: true,
  })
  medico?: MedicoWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => PacienteWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PacienteWhereUniqueInput)
  @IsOptional()
  @Field(() => PacienteWhereUniqueInput, {
    nullable: true,
  })
  paciente?: PacienteWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumCitas02Tipo,
  })
  @IsEnum(EnumCitas02Tipo)
  @IsOptional()
  @Field(() => EnumCitas02Tipo, {
    nullable: true,
  })
  tipo?: "Option1" | null;
}

export { Citas02UpdateInput as Citas02UpdateInput };
