/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Citas02WhereUniqueInput } from "./Citas02WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class DeleteCitas02Args {
  @ApiProperty({
    required: true,
    type: () => Citas02WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Citas02WhereUniqueInput)
  @Field(() => Citas02WhereUniqueInput, { nullable: false })
  where!: Citas02WhereUniqueInput;
}

export { DeleteCitas02Args as DeleteCitas02Args };
