/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { Citas02WhereUniqueInput } from "../../citas02/base/Citas02WhereUniqueInput";
import { ApiProperty } from "@nestjs/swagger";

@InputType()
class Citas02UpdateManyWithoutPacientesInput {
  @Field(() => [Citas02WhereUniqueInput], {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: () => [Citas02WhereUniqueInput],
  })
  connect?: Array<Citas02WhereUniqueInput>;

  @Field(() => [Citas02WhereUniqueInput], {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: () => [Citas02WhereUniqueInput],
  })
  disconnect?: Array<Citas02WhereUniqueInput>;

  @Field(() => [Citas02WhereUniqueInput], {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: () => [Citas02WhereUniqueInput],
  })
  set?: Array<Citas02WhereUniqueInput>;
}

export { Citas02UpdateManyWithoutPacientesInput as Citas02UpdateManyWithoutPacientesInput };
