/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { CitaUpdateManyWithoutPacientesInput } from "./CitaUpdateManyWithoutPacientesInput";
import { Type } from "class-transformer";
import { Citas02UpdateManyWithoutPacientesInput } from "./Citas02UpdateManyWithoutPacientesInput";
import { RecetaUpdateManyWithoutPacientesInput } from "./RecetaUpdateManyWithoutPacientesInput";

@InputType()
class PacienteUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  antecedentes?: string | null;

  @ApiProperty({
    required: false,
    type: () => CitaUpdateManyWithoutPacientesInput,
  })
  @ValidateNested()
  @Type(() => CitaUpdateManyWithoutPacientesInput)
  @IsOptional()
  @Field(() => CitaUpdateManyWithoutPacientesInput, {
    nullable: true,
  })
  citas?: CitaUpdateManyWithoutPacientesInput;

  @ApiProperty({
    required: false,
    type: () => Citas02UpdateManyWithoutPacientesInput,
  })
  @ValidateNested()
  @Type(() => Citas02UpdateManyWithoutPacientesInput)
  @IsOptional()
  @Field(() => Citas02UpdateManyWithoutPacientesInput, {
    nullable: true,
  })
  citas02s?: Citas02UpdateManyWithoutPacientesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  contacto?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  datosDemograficos?: string | null;

  @ApiProperty({
    required: false,
    type: () => RecetaUpdateManyWithoutPacientesInput,
  })
  @ValidateNested()
  @Type(() => RecetaUpdateManyWithoutPacientesInput)
  @IsOptional()
  @Field(() => RecetaUpdateManyWithoutPacientesInput, {
    nullable: true,
  })
  recetas?: RecetaUpdateManyWithoutPacientesInput;
}

export { PacienteUpdateInput as PacienteUpdateInput };
