/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PacienteService } from "../paciente.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PacienteCreateInput } from "./PacienteCreateInput";
import { Paciente } from "./Paciente";
import { PacienteFindManyArgs } from "./PacienteFindManyArgs";
import { PacienteWhereUniqueInput } from "./PacienteWhereUniqueInput";
import { PacienteUpdateInput } from "./PacienteUpdateInput";
import { CitaFindManyArgs } from "../../cita/base/CitaFindManyArgs";
import { Cita } from "../../cita/base/Cita";
import { CitaWhereUniqueInput } from "../../cita/base/CitaWhereUniqueInput";
import { Citas02FindManyArgs } from "../../citas02/base/Citas02FindManyArgs";
import { Citas02 } from "../../citas02/base/Citas02";
import { Citas02WhereUniqueInput } from "../../citas02/base/Citas02WhereUniqueInput";
import { RecetaFindManyArgs } from "../../receta/base/RecetaFindManyArgs";
import { Receta } from "../../receta/base/Receta";
import { RecetaWhereUniqueInput } from "../../receta/base/RecetaWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PacienteControllerBase {
  constructor(
    protected readonly service: PacienteService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Paciente })
  @nestAccessControl.UseRoles({
    resource: "Paciente",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPaciente(
    @common.Body() data: PacienteCreateInput
  ): Promise<Paciente> {
    return await this.service.createPaciente({
      data: data,
      select: {
        antecedentes: true,
        contacto: true,
        createdAt: true,
        datosDemograficos: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Paciente] })
  @ApiNestedQuery(PacienteFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Paciente",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pacientes(@common.Req() request: Request): Promise<Paciente[]> {
    const args = plainToClass(PacienteFindManyArgs, request.query);
    return this.service.pacientes({
      ...args,
      select: {
        antecedentes: true,
        contacto: true,
        createdAt: true,
        datosDemograficos: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Paciente })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Paciente",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async paciente(
    @common.Param() params: PacienteWhereUniqueInput
  ): Promise<Paciente | null> {
    const result = await this.service.paciente({
      where: params,
      select: {
        antecedentes: true,
        contacto: true,
        createdAt: true,
        datosDemograficos: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Paciente })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Paciente",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePaciente(
    @common.Param() params: PacienteWhereUniqueInput,
    @common.Body() data: PacienteUpdateInput
  ): Promise<Paciente | null> {
    try {
      return await this.service.updatePaciente({
        where: params,
        data: data,
        select: {
          antecedentes: true,
          contacto: true,
          createdAt: true,
          datosDemograficos: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Paciente })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Paciente",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePaciente(
    @common.Param() params: PacienteWhereUniqueInput
  ): Promise<Paciente | null> {
    try {
      return await this.service.deletePaciente({
        where: params,
        select: {
          antecedentes: true,
          contacto: true,
          createdAt: true,
          datosDemograficos: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/citas")
  @ApiNestedQuery(CitaFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Cita",
    action: "read",
    possession: "any",
  })
  async findCitas(
    @common.Req() request: Request,
    @common.Param() params: PacienteWhereUniqueInput
  ): Promise<Cita[]> {
    const query = plainToClass(CitaFindManyArgs, request.query);
    const results = await this.service.findCitas(params.id, {
      ...query,
      select: {
        createdAt: true,
        estado: true,
        fecha: true,
        id: true,

        medico: {
          select: {
            id: true,
          },
        },

        paciente: {
          select: {
            id: true,
          },
        },

        tipo: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/citas")
  @nestAccessControl.UseRoles({
    resource: "Paciente",
    action: "update",
    possession: "any",
  })
  async connectCitas(
    @common.Param() params: PacienteWhereUniqueInput,
    @common.Body() body: CitaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      citas: {
        connect: body,
      },
    };
    await this.service.updatePaciente({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/citas")
  @nestAccessControl.UseRoles({
    resource: "Paciente",
    action: "update",
    possession: "any",
  })
  async updateCitas(
    @common.Param() params: PacienteWhereUniqueInput,
    @common.Body() body: CitaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      citas: {
        set: body,
      },
    };
    await this.service.updatePaciente({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/citas")
  @nestAccessControl.UseRoles({
    resource: "Paciente",
    action: "update",
    possession: "any",
  })
  async disconnectCitas(
    @common.Param() params: PacienteWhereUniqueInput,
    @common.Body() body: CitaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      citas: {
        disconnect: body,
      },
    };
    await this.service.updatePaciente({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/citas02s")
  @ApiNestedQuery(Citas02FindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Citas02",
    action: "read",
    possession: "any",
  })
  async findCitas02s(
    @common.Req() request: Request,
    @common.Param() params: PacienteWhereUniqueInput
  ): Promise<Citas02[]> {
    const query = plainToClass(Citas02FindManyArgs, request.query);
    const results = await this.service.findCitas02s(params.id, {
      ...query,
      select: {
        createdAt: true,
        estado: true,
        fechaHora: true,
        id: true,

        medico: {
          select: {
            id: true,
          },
        },

        paciente: {
          select: {
            id: true,
          },
        },

        tipo: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/citas02s")
  @nestAccessControl.UseRoles({
    resource: "Paciente",
    action: "update",
    possession: "any",
  })
  async connectCitas02s(
    @common.Param() params: PacienteWhereUniqueInput,
    @common.Body() body: Citas02WhereUniqueInput[]
  ): Promise<void> {
    const data = {
      citas02s: {
        connect: body,
      },
    };
    await this.service.updatePaciente({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/citas02s")
  @nestAccessControl.UseRoles({
    resource: "Paciente",
    action: "update",
    possession: "any",
  })
  async updateCitas02s(
    @common.Param() params: PacienteWhereUniqueInput,
    @common.Body() body: Citas02WhereUniqueInput[]
  ): Promise<void> {
    const data = {
      citas02s: {
        set: body,
      },
    };
    await this.service.updatePaciente({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/citas02s")
  @nestAccessControl.UseRoles({
    resource: "Paciente",
    action: "update",
    possession: "any",
  })
  async disconnectCitas02s(
    @common.Param() params: PacienteWhereUniqueInput,
    @common.Body() body: Citas02WhereUniqueInput[]
  ): Promise<void> {
    const data = {
      citas02s: {
        disconnect: body,
      },
    };
    await this.service.updatePaciente({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/recetas")
  @ApiNestedQuery(RecetaFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Receta",
    action: "read",
    possession: "any",
  })
  async findRecetas(
    @common.Req() request: Request,
    @common.Param() params: PacienteWhereUniqueInput
  ): Promise<Receta[]> {
    const query = plainToClass(RecetaFindManyArgs, request.query);
    const results = await this.service.findRecetas(params.id, {
      ...query,
      select: {
        createdAt: true,
        fecha: true,
        id: true,
        medicamento: true,

        medico: {
          select: {
            id: true,
          },
        },

        paciente: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/recetas")
  @nestAccessControl.UseRoles({
    resource: "Paciente",
    action: "update",
    possession: "any",
  })
  async connectRecetas(
    @common.Param() params: PacienteWhereUniqueInput,
    @common.Body() body: RecetaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      recetas: {
        connect: body,
      },
    };
    await this.service.updatePaciente({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/recetas")
  @nestAccessControl.UseRoles({
    resource: "Paciente",
    action: "update",
    possession: "any",
  })
  async updateRecetas(
    @common.Param() params: PacienteWhereUniqueInput,
    @common.Body() body: RecetaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      recetas: {
        set: body,
      },
    };
    await this.service.updatePaciente({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/recetas")
  @nestAccessControl.UseRoles({
    resource: "Paciente",
    action: "update",
    possession: "any",
  })
  async disconnectRecetas(
    @common.Param() params: PacienteWhereUniqueInput,
    @common.Body() body: RecetaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      recetas: {
        disconnect: body,
      },
    };
    await this.service.updatePaciente({
      where: params,
      data,
      select: { id: true },
    });
  }
}
