/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Paciente as PrismaPaciente,
  Cita as PrismaCita,
  Citas02 as PrismaCitas02,
  Receta as PrismaReceta,
} from "@prisma/client";

export class PacienteServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.PacienteCountArgs, "select">): Promise<number> {
    return this.prisma.paciente.count(args);
  }

  async pacientes(
    args: Prisma.PacienteFindManyArgs
  ): Promise<PrismaPaciente[]> {
    return this.prisma.paciente.findMany(args);
  }
  async paciente(
    args: Prisma.PacienteFindUniqueArgs
  ): Promise<PrismaPaciente | null> {
    return this.prisma.paciente.findUnique(args);
  }
  async createPaciente(
    args: Prisma.PacienteCreateArgs
  ): Promise<PrismaPaciente> {
    return this.prisma.paciente.create(args);
  }
  async updatePaciente(
    args: Prisma.PacienteUpdateArgs
  ): Promise<PrismaPaciente> {
    return this.prisma.paciente.update(args);
  }
  async deletePaciente(
    args: Prisma.PacienteDeleteArgs
  ): Promise<PrismaPaciente> {
    return this.prisma.paciente.delete(args);
  }

  async findCitas(
    parentId: string,
    args: Prisma.CitaFindManyArgs
  ): Promise<PrismaCita[]> {
    return this.prisma.paciente
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .citas(args);
  }

  async findCitas02s(
    parentId: string,
    args: Prisma.Citas02FindManyArgs
  ): Promise<PrismaCitas02[]> {
    return this.prisma.paciente
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .citas02s(args);
  }

  async findRecetas(
    parentId: string,
    args: Prisma.RecetaFindManyArgs
  ): Promise<PrismaReceta[]> {
    return this.prisma.paciente
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .recetas(args);
  }
}
