/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { CitaCreateNestedManyWithoutPacientesInput } from "./CitaCreateNestedManyWithoutPacientesInput";
import { Type } from "class-transformer";
import { Citas02CreateNestedManyWithoutPacientesInput } from "./Citas02CreateNestedManyWithoutPacientesInput";
import { RecetaCreateNestedManyWithoutPacientesInput } from "./RecetaCreateNestedManyWithoutPacientesInput";

@InputType()
class PacienteCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  antecedentes?: string | null;

  @ApiProperty({
    required: false,
    type: () => CitaCreateNestedManyWithoutPacientesInput,
  })
  @ValidateNested()
  @Type(() => CitaCreateNestedManyWithoutPacientesInput)
  @IsOptional()
  @Field(() => CitaCreateNestedManyWithoutPacientesInput, {
    nullable: true,
  })
  citas?: CitaCreateNestedManyWithoutPacientesInput;

  @ApiProperty({
    required: false,
    type: () => Citas02CreateNestedManyWithoutPacientesInput,
  })
  @ValidateNested()
  @Type(() => Citas02CreateNestedManyWithoutPacientesInput)
  @IsOptional()
  @Field(() => Citas02CreateNestedManyWithoutPacientesInput, {
    nullable: true,
  })
  citas02s?: Citas02CreateNestedManyWithoutPacientesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  contacto?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  datosDemograficos?: string | null;

  @ApiProperty({
    required: false,
    type: () => RecetaCreateNestedManyWithoutPacientesInput,
  })
  @ValidateNested()
  @Type(() => RecetaCreateNestedManyWithoutPacientesInput)
  @IsOptional()
  @Field(() => RecetaCreateNestedManyWithoutPacientesInput, {
    nullable: true,
  })
  recetas?: RecetaCreateNestedManyWithoutPacientesInput;
}

export { PacienteCreateInput as PacienteCreateInput };
