/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsDate,
} from "class-validator";
import { Cita } from "../../cita/base/Cita";
import { Type } from "class-transformer";
import { Citas02 } from "../../citas02/base/Citas02";
import { Receta } from "../../receta/base/Receta";

@ObjectType()
class Paciente {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  antecedentes!: string | null;

  @ApiProperty({
    required: false,
    type: () => [Cita],
  })
  @ValidateNested()
  @Type(() => Cita)
  @IsOptional()
  citas?: Array<Cita>;

  @ApiProperty({
    required: false,
    type: () => [Citas02],
  })
  @ValidateNested()
  @Type(() => Citas02)
  @IsOptional()
  citas02s?: Array<Citas02>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  contacto!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  datosDemograficos!: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: () => [Receta],
  })
  @ValidateNested()
  @Type(() => Receta)
  @IsOptional()
  recetas?: Array<Receta>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Paciente as Paciente };
