/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Clinica as PrismaClinica,
  Empresa as PrismaEmpresa,
} from "@prisma/client";

export class ClinicaServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.ClinicaCountArgs, "select">): Promise<number> {
    return this.prisma.clinica.count(args);
  }

  async clinicas(args: Prisma.ClinicaFindManyArgs): Promise<PrismaClinica[]> {
    return this.prisma.clinica.findMany(args);
  }
  async clinica(
    args: Prisma.ClinicaFindUniqueArgs
  ): Promise<PrismaClinica | null> {
    return this.prisma.clinica.findUnique(args);
  }
  async createClinica(args: Prisma.ClinicaCreateArgs): Promise<PrismaClinica> {
    return this.prisma.clinica.create(args);
  }
  async updateClinica(args: Prisma.ClinicaUpdateArgs): Promise<PrismaClinica> {
    return this.prisma.clinica.update(args);
  }
  async deleteClinica(args: Prisma.ClinicaDeleteArgs): Promise<PrismaClinica> {
    return this.prisma.clinica.delete(args);
  }

  async getEmpresa(parentId: string): Promise<PrismaEmpresa | null> {
    return this.prisma.clinica
      .findUnique({
        where: { id: parentId },
      })
      .empresa();
  }
}
