/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Clinica } from "./Clinica";
import { ClinicaCountArgs } from "./ClinicaCountArgs";
import { ClinicaFindManyArgs } from "./ClinicaFindManyArgs";
import { ClinicaFindUniqueArgs } from "./ClinicaFindUniqueArgs";
import { CreateClinicaArgs } from "./CreateClinicaArgs";
import { UpdateClinicaArgs } from "./UpdateClinicaArgs";
import { DeleteClinicaArgs } from "./DeleteClinicaArgs";
import { Empresa } from "../../empresa/base/Empresa";
import { ClinicaService } from "../clinica.service";
@graphql.Resolver(() => Clinica)
export class ClinicaResolverBase {
  constructor(protected readonly service: ClinicaService) {}

  async _clinicasMeta(
    @graphql.Args() args: ClinicaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Clinica])
  async clinicas(
    @graphql.Args() args: ClinicaFindManyArgs
  ): Promise<Clinica[]> {
    return this.service.clinicas(args);
  }

  @graphql.Query(() => Clinica, { nullable: true })
  async clinica(
    @graphql.Args() args: ClinicaFindUniqueArgs
  ): Promise<Clinica | null> {
    const result = await this.service.clinica(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Clinica)
  async createClinica(
    @graphql.Args() args: CreateClinicaArgs
  ): Promise<Clinica> {
    return await this.service.createClinica({
      ...args,
      data: {
        ...args.data,

        empresa: args.data.empresa
          ? {
              connect: args.data.empresa,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Clinica)
  async updateClinica(
    @graphql.Args() args: UpdateClinicaArgs
  ): Promise<Clinica | null> {
    try {
      return await this.service.updateClinica({
        ...args,
        data: {
          ...args.data,

          empresa: args.data.empresa
            ? {
                connect: args.data.empresa,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Clinica)
  async deleteClinica(
    @graphql.Args() args: DeleteClinicaArgs
  ): Promise<Clinica | null> {
    try {
      return await this.service.deleteClinica(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Empresa, {
    nullable: true,
    name: "empresa",
  })
  async getEmpresa(@graphql.Parent() parent: Clinica): Promise<Empresa | null> {
    const result = await this.service.getEmpresa(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
