/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ClinicaService } from "../clinica.service";
import { ClinicaCreateInput } from "./ClinicaCreateInput";
import { Clinica } from "./Clinica";
import { ClinicaFindManyArgs } from "./ClinicaFindManyArgs";
import { ClinicaWhereUniqueInput } from "./ClinicaWhereUniqueInput";
import { ClinicaUpdateInput } from "./ClinicaUpdateInput";

export class ClinicaControllerBase {
  constructor(protected readonly service: ClinicaService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Clinica })
  async createClinica(
    @common.Body() data: ClinicaCreateInput
  ): Promise<Clinica> {
    return await this.service.createClinica({
      data: {
        ...data,

        empresa: data.empresa
          ? {
              connect: data.empresa,
            }
          : undefined,
      },
      select: {
        activa: true,
        ciudad: true,
        cp: true,
        createdAt: true,
        dir: true,

        empresa: {
          select: {
            id: true,
          },
        },

        estado: true,
        id: true,
        nombreComercial: true,
        razonSocial: true,
        tel: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Clinica] })
  @ApiNestedQuery(ClinicaFindManyArgs)
  async clinicas(@common.Req() request: Request): Promise<Clinica[]> {
    const args = plainToClass(ClinicaFindManyArgs, request.query);
    return this.service.clinicas({
      ...args,
      select: {
        activa: true,
        ciudad: true,
        cp: true,
        createdAt: true,
        dir: true,

        empresa: {
          select: {
            id: true,
          },
        },

        estado: true,
        id: true,
        nombreComercial: true,
        razonSocial: true,
        tel: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Clinica })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async clinica(
    @common.Param() params: ClinicaWhereUniqueInput
  ): Promise<Clinica | null> {
    const result = await this.service.clinica({
      where: params,
      select: {
        activa: true,
        ciudad: true,
        cp: true,
        createdAt: true,
        dir: true,

        empresa: {
          select: {
            id: true,
          },
        },

        estado: true,
        id: true,
        nombreComercial: true,
        razonSocial: true,
        tel: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Clinica })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateClinica(
    @common.Param() params: ClinicaWhereUniqueInput,
    @common.Body() data: ClinicaUpdateInput
  ): Promise<Clinica | null> {
    try {
      return await this.service.updateClinica({
        where: params,
        data: {
          ...data,

          empresa: data.empresa
            ? {
                connect: data.empresa,
              }
            : undefined,
        },
        select: {
          activa: true,
          ciudad: true,
          cp: true,
          createdAt: true,
          dir: true,

          empresa: {
            select: {
              id: true,
            },
          },

          estado: true,
          id: true,
          nombreComercial: true,
          razonSocial: true,
          tel: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Clinica })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteClinica(
    @common.Param() params: ClinicaWhereUniqueInput
  ): Promise<Clinica | null> {
    try {
      return await this.service.deleteClinica({
        where: params,
        select: {
          activa: true,
          ciudad: true,
          cp: true,
          createdAt: true,
          dir: true,

          empresa: {
            select: {
              id: true,
            },
          },

          estado: true,
          id: true,
          nombreComercial: true,
          razonSocial: true,
          tel: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
