/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Cita } from "./Cita";
import { CitaCountArgs } from "./CitaCountArgs";
import { CitaFindManyArgs } from "./CitaFindManyArgs";
import { CitaFindUniqueArgs } from "./CitaFindUniqueArgs";
import { CreateCitaArgs } from "./CreateCitaArgs";
import { UpdateCitaArgs } from "./UpdateCitaArgs";
import { DeleteCitaArgs } from "./DeleteCitaArgs";
import { Medico } from "../../medico/base/Medico";
import { Paciente } from "../../paciente/base/Paciente";
import { CitaService } from "../cita.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Cita)
export class CitaResolverBase {
  constructor(
    protected readonly service: CitaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Cita",
    action: "read",
    possession: "any",
  })
  async _citasMeta(
    @graphql.Args() args: CitaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Cita])
  @nestAccessControl.UseRoles({
    resource: "Cita",
    action: "read",
    possession: "any",
  })
  async citas(@graphql.Args() args: CitaFindManyArgs): Promise<Cita[]> {
    return this.service.citas(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Cita, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Cita",
    action: "read",
    possession: "own",
  })
  async cita(@graphql.Args() args: CitaFindUniqueArgs): Promise<Cita | null> {
    const result = await this.service.cita(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Cita)
  @nestAccessControl.UseRoles({
    resource: "Cita",
    action: "create",
    possession: "any",
  })
  async createCita(@graphql.Args() args: CreateCitaArgs): Promise<Cita> {
    return await this.service.createCita({
      ...args,
      data: {
        ...args.data,

        medico: args.data.medico
          ? {
              connect: args.data.medico,
            }
          : undefined,

        paciente: args.data.paciente
          ? {
              connect: args.data.paciente,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Cita)
  @nestAccessControl.UseRoles({
    resource: "Cita",
    action: "update",
    possession: "any",
  })
  async updateCita(@graphql.Args() args: UpdateCitaArgs): Promise<Cita | null> {
    try {
      return await this.service.updateCita({
        ...args,
        data: {
          ...args.data,

          medico: args.data.medico
            ? {
                connect: args.data.medico,
              }
            : undefined,

          paciente: args.data.paciente
            ? {
                connect: args.data.paciente,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Cita)
  @nestAccessControl.UseRoles({
    resource: "Cita",
    action: "delete",
    possession: "any",
  })
  async deleteCita(@graphql.Args() args: DeleteCitaArgs): Promise<Cita | null> {
    try {
      return await this.service.deleteCita(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Medico, {
    nullable: true,
    name: "medico",
  })
  @nestAccessControl.UseRoles({
    resource: "Medico",
    action: "read",
    possession: "any",
  })
  async getMedico(@graphql.Parent() parent: Cita): Promise<Medico | null> {
    const result = await this.service.getMedico(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Paciente, {
    nullable: true,
    name: "paciente",
  })
  @nestAccessControl.UseRoles({
    resource: "Paciente",
    action: "read",
    possession: "any",
  })
  async getPaciente(@graphql.Parent() parent: Cita): Promise<Paciente | null> {
    const result = await this.service.getPaciente(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
