/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Cita as PrismaCita,
  Medico as PrismaMedico,
  Paciente as PrismaPaciente,
} from "@prisma/client";

export class CitaServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.CitaCountArgs, "select">): Promise<number> {
    return this.prisma.cita.count(args);
  }

  async citas(args: Prisma.CitaFindManyArgs): Promise<PrismaCita[]> {
    return this.prisma.cita.findMany(args);
  }
  async cita(args: Prisma.CitaFindUniqueArgs): Promise<PrismaCita | null> {
    return this.prisma.cita.findUnique(args);
  }
  async createCita(args: Prisma.CitaCreateArgs): Promise<PrismaCita> {
    return this.prisma.cita.create(args);
  }
  async updateCita(args: Prisma.CitaUpdateArgs): Promise<PrismaCita> {
    return this.prisma.cita.update(args);
  }
  async deleteCita(args: Prisma.CitaDeleteArgs): Promise<PrismaCita> {
    return this.prisma.cita.delete(args);
  }

  async getMedico(parentId: string): Promise<PrismaMedico | null> {
    return this.prisma.cita
      .findUnique({
        where: { id: parentId },
      })
      .medico();
  }

  async getPaciente(parentId: string): Promise<PrismaPaciente | null> {
    return this.prisma.cita
      .findUnique({
        where: { id: parentId },
      })
      .paciente();
  }
}
