/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CitaService } from "../cita.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CitaCreateInput } from "./CitaCreateInput";
import { Cita } from "./Cita";
import { CitaFindManyArgs } from "./CitaFindManyArgs";
import { CitaWhereUniqueInput } from "./CitaWhereUniqueInput";
import { CitaUpdateInput } from "./CitaUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CitaControllerBase {
  constructor(
    protected readonly service: CitaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Cita })
  @nestAccessControl.UseRoles({
    resource: "Cita",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCita(@common.Body() data: CitaCreateInput): Promise<Cita> {
    return await this.service.createCita({
      data: {
        ...data,

        medico: data.medico
          ? {
              connect: data.medico,
            }
          : undefined,

        paciente: data.paciente
          ? {
              connect: data.paciente,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        estado: true,
        fecha: true,
        id: true,

        medico: {
          select: {
            id: true,
          },
        },

        paciente: {
          select: {
            id: true,
          },
        },

        tipo: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Cita] })
  @ApiNestedQuery(CitaFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Cita",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async citas(@common.Req() request: Request): Promise<Cita[]> {
    const args = plainToClass(CitaFindManyArgs, request.query);
    return this.service.citas({
      ...args,
      select: {
        createdAt: true,
        estado: true,
        fecha: true,
        id: true,

        medico: {
          select: {
            id: true,
          },
        },

        paciente: {
          select: {
            id: true,
          },
        },

        tipo: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Cita })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Cita",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async cita(
    @common.Param() params: CitaWhereUniqueInput
  ): Promise<Cita | null> {
    const result = await this.service.cita({
      where: params,
      select: {
        createdAt: true,
        estado: true,
        fecha: true,
        id: true,

        medico: {
          select: {
            id: true,
          },
        },

        paciente: {
          select: {
            id: true,
          },
        },

        tipo: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Cita })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Cita",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCita(
    @common.Param() params: CitaWhereUniqueInput,
    @common.Body() data: CitaUpdateInput
  ): Promise<Cita | null> {
    try {
      return await this.service.updateCita({
        where: params,
        data: {
          ...data,

          medico: data.medico
            ? {
                connect: data.medico,
              }
            : undefined,

          paciente: data.paciente
            ? {
                connect: data.paciente,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          estado: true,
          fecha: true,
          id: true,

          medico: {
            select: {
              id: true,
            },
          },

          paciente: {
            select: {
              id: true,
            },
          },

          tipo: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Cita })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Cita",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCita(
    @common.Param() params: CitaWhereUniqueInput
  ): Promise<Cita | null> {
    try {
      return await this.service.deleteCita({
        where: params,
        select: {
          createdAt: true,
          estado: true,
          fecha: true,
          id: true,

          medico: {
            select: {
              id: true,
            },
          },

          paciente: {
            select: {
              id: true,
            },
          },

          tipo: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
