/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { CitaCreateNestedManyWithoutMedicosInput } from "./CitaCreateNestedManyWithoutMedicosInput";
import { Type } from "class-transformer";
import { Citas02CreateNestedManyWithoutMedicosInput } from "./Citas02CreateNestedManyWithoutMedicosInput";
import { RecetaCreateNestedManyWithoutMedicosInput } from "./RecetaCreateNestedManyWithoutMedicosInput";

@InputType()
class MedicoCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  cedula?: string | null;

  @ApiProperty({
    required: false,
    type: () => CitaCreateNestedManyWithoutMedicosInput,
  })
  @ValidateNested()
  @Type(() => CitaCreateNestedManyWithoutMedicosInput)
  @IsOptional()
  @Field(() => CitaCreateNestedManyWithoutMedicosInput, {
    nullable: true,
  })
  citas?: CitaCreateNestedManyWithoutMedicosInput;

  @ApiProperty({
    required: false,
    type: () => Citas02CreateNestedManyWithoutMedicosInput,
  })
  @ValidateNested()
  @Type(() => Citas02CreateNestedManyWithoutMedicosInput)
  @IsOptional()
  @Field(() => Citas02CreateNestedManyWithoutMedicosInput, {
    nullable: true,
  })
  citas02s?: Citas02CreateNestedManyWithoutMedicosInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  especialidad?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  horarios?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  perfil?: string | null;

  @ApiProperty({
    required: false,
    type: () => RecetaCreateNestedManyWithoutMedicosInput,
  })
  @ValidateNested()
  @Type(() => RecetaCreateNestedManyWithoutMedicosInput)
  @IsOptional()
  @Field(() => RecetaCreateNestedManyWithoutMedicosInput, {
    nullable: true,
  })
  recetas?: RecetaCreateNestedManyWithoutMedicosInput;
}

export { MedicoCreateInput as MedicoCreateInput };
