/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Medico as PrismaMedico,
  Cita as PrismaCita,
  Citas02 as PrismaCitas02,
  Receta as PrismaReceta,
} from "@prisma/client";

export class MedicoServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.MedicoCountArgs, "select">): Promise<number> {
    return this.prisma.medico.count(args);
  }

  async medicos(args: Prisma.MedicoFindManyArgs): Promise<PrismaMedico[]> {
    return this.prisma.medico.findMany(args);
  }
  async medico(
    args: Prisma.MedicoFindUniqueArgs
  ): Promise<PrismaMedico | null> {
    return this.prisma.medico.findUnique(args);
  }
  async createMedico(args: Prisma.MedicoCreateArgs): Promise<PrismaMedico> {
    return this.prisma.medico.create(args);
  }
  async updateMedico(args: Prisma.MedicoUpdateArgs): Promise<PrismaMedico> {
    return this.prisma.medico.update(args);
  }
  async deleteMedico(args: Prisma.MedicoDeleteArgs): Promise<PrismaMedico> {
    return this.prisma.medico.delete(args);
  }

  async findCitas(
    parentId: string,
    args: Prisma.CitaFindManyArgs
  ): Promise<PrismaCita[]> {
    return this.prisma.medico
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .citas(args);
  }

  async findCitas02s(
    parentId: string,
    args: Prisma.Citas02FindManyArgs
  ): Promise<PrismaCitas02[]> {
    return this.prisma.medico
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .citas02s(args);
  }

  async findRecetas(
    parentId: string,
    args: Prisma.RecetaFindManyArgs
  ): Promise<PrismaReceta[]> {
    return this.prisma.medico
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .recetas(args);
  }
}
