/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Medico } from "./Medico";
import { MedicoCountArgs } from "./MedicoCountArgs";
import { MedicoFindManyArgs } from "./MedicoFindManyArgs";
import { MedicoFindUniqueArgs } from "./MedicoFindUniqueArgs";
import { CreateMedicoArgs } from "./CreateMedicoArgs";
import { UpdateMedicoArgs } from "./UpdateMedicoArgs";
import { DeleteMedicoArgs } from "./DeleteMedicoArgs";
import { CitaFindManyArgs } from "../../cita/base/CitaFindManyArgs";
import { Cita } from "../../cita/base/Cita";
import { Citas02FindManyArgs } from "../../citas02/base/Citas02FindManyArgs";
import { Citas02 } from "../../citas02/base/Citas02";
import { RecetaFindManyArgs } from "../../receta/base/RecetaFindManyArgs";
import { Receta } from "../../receta/base/Receta";
import { MedicoService } from "../medico.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Medico)
export class MedicoResolverBase {
  constructor(
    protected readonly service: MedicoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Medico",
    action: "read",
    possession: "any",
  })
  async _medicosMeta(
    @graphql.Args() args: MedicoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Medico])
  @nestAccessControl.UseRoles({
    resource: "Medico",
    action: "read",
    possession: "any",
  })
  async medicos(@graphql.Args() args: MedicoFindManyArgs): Promise<Medico[]> {
    return this.service.medicos(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Medico, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Medico",
    action: "read",
    possession: "own",
  })
  async medico(
    @graphql.Args() args: MedicoFindUniqueArgs
  ): Promise<Medico | null> {
    const result = await this.service.medico(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Medico)
  @nestAccessControl.UseRoles({
    resource: "Medico",
    action: "create",
    possession: "any",
  })
  async createMedico(@graphql.Args() args: CreateMedicoArgs): Promise<Medico> {
    return await this.service.createMedico({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Medico)
  @nestAccessControl.UseRoles({
    resource: "Medico",
    action: "update",
    possession: "any",
  })
  async updateMedico(
    @graphql.Args() args: UpdateMedicoArgs
  ): Promise<Medico | null> {
    try {
      return await this.service.updateMedico({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Medico)
  @nestAccessControl.UseRoles({
    resource: "Medico",
    action: "delete",
    possession: "any",
  })
  async deleteMedico(
    @graphql.Args() args: DeleteMedicoArgs
  ): Promise<Medico | null> {
    try {
      return await this.service.deleteMedico(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Cita], { name: "citas" })
  @nestAccessControl.UseRoles({
    resource: "Cita",
    action: "read",
    possession: "any",
  })
  async findCitas(
    @graphql.Parent() parent: Medico,
    @graphql.Args() args: CitaFindManyArgs
  ): Promise<Cita[]> {
    const results = await this.service.findCitas(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Citas02], { name: "citas02s" })
  @nestAccessControl.UseRoles({
    resource: "Citas02",
    action: "read",
    possession: "any",
  })
  async findCitas02s(
    @graphql.Parent() parent: Medico,
    @graphql.Args() args: Citas02FindManyArgs
  ): Promise<Citas02[]> {
    const results = await this.service.findCitas02s(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Receta], { name: "recetas" })
  @nestAccessControl.UseRoles({
    resource: "Receta",
    action: "read",
    possession: "any",
  })
  async findRecetas(
    @graphql.Parent() parent: Medico,
    @graphql.Args() args: RecetaFindManyArgs
  ): Promise<Receta[]> {
    const results = await this.service.findRecetas(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
