/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MedicoService } from "../medico.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MedicoCreateInput } from "./MedicoCreateInput";
import { Medico } from "./Medico";
import { MedicoFindManyArgs } from "./MedicoFindManyArgs";
import { MedicoWhereUniqueInput } from "./MedicoWhereUniqueInput";
import { MedicoUpdateInput } from "./MedicoUpdateInput";
import { CitaFindManyArgs } from "../../cita/base/CitaFindManyArgs";
import { Cita } from "../../cita/base/Cita";
import { CitaWhereUniqueInput } from "../../cita/base/CitaWhereUniqueInput";
import { Citas02FindManyArgs } from "../../citas02/base/Citas02FindManyArgs";
import { Citas02 } from "../../citas02/base/Citas02";
import { Citas02WhereUniqueInput } from "../../citas02/base/Citas02WhereUniqueInput";
import { RecetaFindManyArgs } from "../../receta/base/RecetaFindManyArgs";
import { Receta } from "../../receta/base/Receta";
import { RecetaWhereUniqueInput } from "../../receta/base/RecetaWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MedicoControllerBase {
  constructor(
    protected readonly service: MedicoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Medico })
  @nestAccessControl.UseRoles({
    resource: "Medico",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMedico(@common.Body() data: MedicoCreateInput): Promise<Medico> {
    return await this.service.createMedico({
      data: data,
      select: {
        cedula: true,
        createdAt: true,
        especialidad: true,
        horarios: true,
        id: true,
        perfil: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Medico] })
  @ApiNestedQuery(MedicoFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Medico",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async medicos(@common.Req() request: Request): Promise<Medico[]> {
    const args = plainToClass(MedicoFindManyArgs, request.query);
    return this.service.medicos({
      ...args,
      select: {
        cedula: true,
        createdAt: true,
        especialidad: true,
        horarios: true,
        id: true,
        perfil: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Medico })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Medico",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async medico(
    @common.Param() params: MedicoWhereUniqueInput
  ): Promise<Medico | null> {
    const result = await this.service.medico({
      where: params,
      select: {
        cedula: true,
        createdAt: true,
        especialidad: true,
        horarios: true,
        id: true,
        perfil: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Medico })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Medico",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMedico(
    @common.Param() params: MedicoWhereUniqueInput,
    @common.Body() data: MedicoUpdateInput
  ): Promise<Medico | null> {
    try {
      return await this.service.updateMedico({
        where: params,
        data: data,
        select: {
          cedula: true,
          createdAt: true,
          especialidad: true,
          horarios: true,
          id: true,
          perfil: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Medico })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Medico",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMedico(
    @common.Param() params: MedicoWhereUniqueInput
  ): Promise<Medico | null> {
    try {
      return await this.service.deleteMedico({
        where: params,
        select: {
          cedula: true,
          createdAt: true,
          especialidad: true,
          horarios: true,
          id: true,
          perfil: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/citas")
  @ApiNestedQuery(CitaFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Cita",
    action: "read",
    possession: "any",
  })
  async findCitas(
    @common.Req() request: Request,
    @common.Param() params: MedicoWhereUniqueInput
  ): Promise<Cita[]> {
    const query = plainToClass(CitaFindManyArgs, request.query);
    const results = await this.service.findCitas(params.id, {
      ...query,
      select: {
        createdAt: true,
        estado: true,
        fecha: true,
        id: true,

        medico: {
          select: {
            id: true,
          },
        },

        paciente: {
          select: {
            id: true,
          },
        },

        tipo: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/citas")
  @nestAccessControl.UseRoles({
    resource: "Medico",
    action: "update",
    possession: "any",
  })
  async connectCitas(
    @common.Param() params: MedicoWhereUniqueInput,
    @common.Body() body: CitaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      citas: {
        connect: body,
      },
    };
    await this.service.updateMedico({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/citas")
  @nestAccessControl.UseRoles({
    resource: "Medico",
    action: "update",
    possession: "any",
  })
  async updateCitas(
    @common.Param() params: MedicoWhereUniqueInput,
    @common.Body() body: CitaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      citas: {
        set: body,
      },
    };
    await this.service.updateMedico({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/citas")
  @nestAccessControl.UseRoles({
    resource: "Medico",
    action: "update",
    possession: "any",
  })
  async disconnectCitas(
    @common.Param() params: MedicoWhereUniqueInput,
    @common.Body() body: CitaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      citas: {
        disconnect: body,
      },
    };
    await this.service.updateMedico({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/citas02s")
  @ApiNestedQuery(Citas02FindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Citas02",
    action: "read",
    possession: "any",
  })
  async findCitas02s(
    @common.Req() request: Request,
    @common.Param() params: MedicoWhereUniqueInput
  ): Promise<Citas02[]> {
    const query = plainToClass(Citas02FindManyArgs, request.query);
    const results = await this.service.findCitas02s(params.id, {
      ...query,
      select: {
        createdAt: true,
        estado: true,
        fechaHora: true,
        id: true,

        medico: {
          select: {
            id: true,
          },
        },

        paciente: {
          select: {
            id: true,
          },
        },

        tipo: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/citas02s")
  @nestAccessControl.UseRoles({
    resource: "Medico",
    action: "update",
    possession: "any",
  })
  async connectCitas02s(
    @common.Param() params: MedicoWhereUniqueInput,
    @common.Body() body: Citas02WhereUniqueInput[]
  ): Promise<void> {
    const data = {
      citas02s: {
        connect: body,
      },
    };
    await this.service.updateMedico({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/citas02s")
  @nestAccessControl.UseRoles({
    resource: "Medico",
    action: "update",
    possession: "any",
  })
  async updateCitas02s(
    @common.Param() params: MedicoWhereUniqueInput,
    @common.Body() body: Citas02WhereUniqueInput[]
  ): Promise<void> {
    const data = {
      citas02s: {
        set: body,
      },
    };
    await this.service.updateMedico({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/citas02s")
  @nestAccessControl.UseRoles({
    resource: "Medico",
    action: "update",
    possession: "any",
  })
  async disconnectCitas02s(
    @common.Param() params: MedicoWhereUniqueInput,
    @common.Body() body: Citas02WhereUniqueInput[]
  ): Promise<void> {
    const data = {
      citas02s: {
        disconnect: body,
      },
    };
    await this.service.updateMedico({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/recetas")
  @ApiNestedQuery(RecetaFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Receta",
    action: "read",
    possession: "any",
  })
  async findRecetas(
    @common.Req() request: Request,
    @common.Param() params: MedicoWhereUniqueInput
  ): Promise<Receta[]> {
    const query = plainToClass(RecetaFindManyArgs, request.query);
    const results = await this.service.findRecetas(params.id, {
      ...query,
      select: {
        createdAt: true,
        fecha: true,
        id: true,
        medicamento: true,

        medico: {
          select: {
            id: true,
          },
        },

        paciente: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/recetas")
  @nestAccessControl.UseRoles({
    resource: "Medico",
    action: "update",
    possession: "any",
  })
  async connectRecetas(
    @common.Param() params: MedicoWhereUniqueInput,
    @common.Body() body: RecetaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      recetas: {
        connect: body,
      },
    };
    await this.service.updateMedico({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/recetas")
  @nestAccessControl.UseRoles({
    resource: "Medico",
    action: "update",
    possession: "any",
  })
  async updateRecetas(
    @common.Param() params: MedicoWhereUniqueInput,
    @common.Body() body: RecetaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      recetas: {
        set: body,
      },
    };
    await this.service.updateMedico({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/recetas")
  @nestAccessControl.UseRoles({
    resource: "Medico",
    action: "update",
    possession: "any",
  })
  async disconnectRecetas(
    @common.Param() params: MedicoWhereUniqueInput,
    @common.Body() body: RecetaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      recetas: {
        disconnect: body,
      },
    };
    await this.service.updateMedico({
      where: params,
      data,
      select: { id: true },
    });
  }
}
