/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { CitaUpdateManyWithoutMedicosInput } from "./CitaUpdateManyWithoutMedicosInput";
import { Type } from "class-transformer";
import { Citas02UpdateManyWithoutMedicosInput } from "./Citas02UpdateManyWithoutMedicosInput";
import { RecetaUpdateManyWithoutMedicosInput } from "./RecetaUpdateManyWithoutMedicosInput";

@InputType()
class MedicoUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  cedula?: string | null;

  @ApiProperty({
    required: false,
    type: () => CitaUpdateManyWithoutMedicosInput,
  })
  @ValidateNested()
  @Type(() => CitaUpdateManyWithoutMedicosInput)
  @IsOptional()
  @Field(() => CitaUpdateManyWithoutMedicosInput, {
    nullable: true,
  })
  citas?: CitaUpdateManyWithoutMedicosInput;

  @ApiProperty({
    required: false,
    type: () => Citas02UpdateManyWithoutMedicosInput,
  })
  @ValidateNested()
  @Type(() => Citas02UpdateManyWithoutMedicosInput)
  @IsOptional()
  @Field(() => Citas02UpdateManyWithoutMedicosInput, {
    nullable: true,
  })
  citas02s?: Citas02UpdateManyWithoutMedicosInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  especialidad?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  horarios?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  perfil?: string | null;

  @ApiProperty({
    required: false,
    type: () => RecetaUpdateManyWithoutMedicosInput,
  })
  @ValidateNested()
  @Type(() => RecetaUpdateManyWithoutMedicosInput)
  @IsOptional()
  @Field(() => RecetaUpdateManyWithoutMedicosInput, {
    nullable: true,
  })
  recetas?: RecetaUpdateManyWithoutMedicosInput;
}

export { MedicoUpdateInput as MedicoUpdateInput };
