/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { CitaListRelationFilter } from "../../cita/base/CitaListRelationFilter";
import { Citas02ListRelationFilter } from "../../citas02/base/Citas02ListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { RecetaListRelationFilter } from "../../receta/base/RecetaListRelationFilter";

@InputType()
class MedicoWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  cedula?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => CitaListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CitaListRelationFilter)
  @IsOptional()
  @Field(() => CitaListRelationFilter, {
    nullable: true,
  })
  citas?: CitaListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => Citas02ListRelationFilter,
  })
  @ValidateNested()
  @Type(() => Citas02ListRelationFilter)
  @IsOptional()
  @Field(() => Citas02ListRelationFilter, {
    nullable: true,
  })
  citas02s?: Citas02ListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  especialidad?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  horarios?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  perfil?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => RecetaListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RecetaListRelationFilter)
  @IsOptional()
  @Field(() => RecetaListRelationFilter, {
    nullable: true,
  })
  recetas?: RecetaListRelationFilter;
}

export { MedicoWhereInput as MedicoWhereInput };
