/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Empresa as PrismaEmpresa } from "@prisma/client";

export class EmpresaServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.EmpresaCountArgs, "select">): Promise<number> {
    return this.prisma.empresa.count(args);
  }

  async empresas(args: Prisma.EmpresaFindManyArgs): Promise<PrismaEmpresa[]> {
    return this.prisma.empresa.findMany(args);
  }
  async empresa(
    args: Prisma.EmpresaFindUniqueArgs
  ): Promise<PrismaEmpresa | null> {
    return this.prisma.empresa.findUnique(args);
  }
  async createEmpresa(args: Prisma.EmpresaCreateArgs): Promise<PrismaEmpresa> {
    return this.prisma.empresa.create(args);
  }
  async updateEmpresa(args: Prisma.EmpresaUpdateArgs): Promise<PrismaEmpresa> {
    return this.prisma.empresa.update(args);
  }
  async deleteEmpresa(args: Prisma.EmpresaDeleteArgs): Promise<PrismaEmpresa> {
    return this.prisma.empresa.delete(args);
  }
}
