/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Empresa } from "./Empresa";
import { EmpresaCountArgs } from "./EmpresaCountArgs";
import { EmpresaFindManyArgs } from "./EmpresaFindManyArgs";
import { EmpresaFindUniqueArgs } from "./EmpresaFindUniqueArgs";
import { CreateEmpresaArgs } from "./CreateEmpresaArgs";
import { UpdateEmpresaArgs } from "./UpdateEmpresaArgs";
import { DeleteEmpresaArgs } from "./DeleteEmpresaArgs";
import { ClinicaFindManyArgs } from "../../clinica/base/ClinicaFindManyArgs";
import { Clinica } from "../../clinica/base/Clinica";
import { EmpresaService } from "../empresa.service";
@graphql.Resolver(() => Empresa)
export class EmpresaResolverBase {
  constructor(protected readonly service: EmpresaService) {}

  async _empresasMeta(
    @graphql.Args() args: EmpresaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Empresa])
  async empresas(
    @graphql.Args() args: EmpresaFindManyArgs
  ): Promise<Empresa[]> {
    return this.service.empresas(args);
  }

  @graphql.Query(() => Empresa, { nullable: true })
  async empresa(
    @graphql.Args() args: EmpresaFindUniqueArgs
  ): Promise<Empresa | null> {
    const result = await this.service.empresa(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Empresa)
  async createEmpresa(
    @graphql.Args() args: CreateEmpresaArgs
  ): Promise<Empresa> {
    return await this.service.createEmpresa({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Empresa)
  async updateEmpresa(
    @graphql.Args() args: UpdateEmpresaArgs
  ): Promise<Empresa | null> {
    try {
      return await this.service.updateEmpresa({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Empresa)
  async deleteEmpresa(
    @graphql.Args() args: DeleteEmpresaArgs
  ): Promise<Empresa | null> {
    try {
      return await this.service.deleteEmpresa(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Clinica], { name: "clinicas" })
  async findClinicas(
    @graphql.Parent() parent: Empresa,
    @graphql.Args() args: ClinicaFindManyArgs
  ): Promise<Clinica[]> {
    const results = await this.service.findClinicas(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
