/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { EmpresaService } from "../empresa.service";
import { EmpresaCreateInput } from "./EmpresaCreateInput";
import { Empresa } from "./Empresa";
import { EmpresaFindManyArgs } from "./EmpresaFindManyArgs";
import { EmpresaWhereUniqueInput } from "./EmpresaWhereUniqueInput";
import { EmpresaUpdateInput } from "./EmpresaUpdateInput";
import { ClinicaFindManyArgs } from "../../clinica/base/ClinicaFindManyArgs";
import { Clinica } from "../../clinica/base/Clinica";
import { ClinicaWhereUniqueInput } from "../../clinica/base/ClinicaWhereUniqueInput";

export class EmpresaControllerBase {
  constructor(protected readonly service: EmpresaService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Empresa })
  async createEmpresa(
    @common.Body() data: EmpresaCreateInput
  ): Promise<Empresa> {
    return await this.service.createEmpresa({
      data: data,
      select: {
        createdAt: true,
        direccion: true,
        id: true,
        nombreComercial: true,
        razonSocial: true,
        rfc: true,
        telefono: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Empresa] })
  @ApiNestedQuery(EmpresaFindManyArgs)
  async empresas(@common.Req() request: Request): Promise<Empresa[]> {
    const args = plainToClass(EmpresaFindManyArgs, request.query);
    return this.service.empresas({
      ...args,
      select: {
        createdAt: true,
        direccion: true,
        id: true,
        nombreComercial: true,
        razonSocial: true,
        rfc: true,
        telefono: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Empresa })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async empresa(
    @common.Param() params: EmpresaWhereUniqueInput
  ): Promise<Empresa | null> {
    const result = await this.service.empresa({
      where: params,
      select: {
        createdAt: true,
        direccion: true,
        id: true,
        nombreComercial: true,
        razonSocial: true,
        rfc: true,
        telefono: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Empresa })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateEmpresa(
    @common.Param() params: EmpresaWhereUniqueInput,
    @common.Body() data: EmpresaUpdateInput
  ): Promise<Empresa | null> {
    try {
      return await this.service.updateEmpresa({
        where: params,
        data: data,
        select: {
          createdAt: true,
          direccion: true,
          id: true,
          nombreComercial: true,
          razonSocial: true,
          rfc: true,
          telefono: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Empresa })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteEmpresa(
    @common.Param() params: EmpresaWhereUniqueInput
  ): Promise<Empresa | null> {
    try {
      return await this.service.deleteEmpresa({
        where: params,
        select: {
          createdAt: true,
          direccion: true,
          id: true,
          nombreComercial: true,
          razonSocial: true,
          rfc: true,
          telefono: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/clinicas")
  @ApiNestedQuery(ClinicaFindManyArgs)
  async findClinicas(
    @common.Req() request: Request,
    @common.Param() params: EmpresaWhereUniqueInput
  ): Promise<Clinica[]> {
    const query = plainToClass(ClinicaFindManyArgs, request.query);
    const results = await this.service.findClinicas(params.id, {
      ...query,
      select: {
        activa: true,
        ciudad: true,
        cp: true,
        createdAt: true,
        dir: true,

        empresa: {
          select: {
            id: true,
          },
        },

        estado: true,
        id: true,
        nombreComercial: true,
        razonSocial: true,
        tel: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/clinicas")
  async connectClinicas(
    @common.Param() params: EmpresaWhereUniqueInput,
    @common.Body() body: ClinicaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      clinicas: {
        connect: body,
      },
    };
    await this.service.updateEmpresa({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/clinicas")
  async updateClinicas(
    @common.Param() params: EmpresaWhereUniqueInput,
    @common.Body() body: ClinicaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      clinicas: {
        set: body,
      },
    };
    await this.service.updateEmpresa({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/clinicas")
  async disconnectClinicas(
    @common.Param() params: EmpresaWhereUniqueInput,
    @common.Body() body: ClinicaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      clinicas: {
        disconnect: body,
      },
    };
    await this.service.updateEmpresa({
      where: params,
      data,
      select: { id: true },
    });
  }
}
