/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MedicamentoService } from "../medicamento.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MedicamentoCreateInput } from "./MedicamentoCreateInput";
import { Medicamento } from "./Medicamento";
import { MedicamentoFindManyArgs } from "./MedicamentoFindManyArgs";
import { MedicamentoWhereUniqueInput } from "./MedicamentoWhereUniqueInput";
import { MedicamentoUpdateInput } from "./MedicamentoUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MedicamentoControllerBase {
  constructor(
    protected readonly service: MedicamentoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Medicamento })
  @nestAccessControl.UseRoles({
    resource: "Medicamento",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMedicamento(
    @common.Body() data: MedicamentoCreateInput
  ): Promise<Medicamento> {
    return await this.service.createMedicamento({
      data: data,
      select: {
        createdAt: true,
        dosis: true,
        id: true,
        nombre: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Medicamento] })
  @ApiNestedQuery(MedicamentoFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Medicamento",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async medicamentos(@common.Req() request: Request): Promise<Medicamento[]> {
    const args = plainToClass(MedicamentoFindManyArgs, request.query);
    return this.service.medicamentos({
      ...args,
      select: {
        createdAt: true,
        dosis: true,
        id: true,
        nombre: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Medicamento })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Medicamento",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async medicamento(
    @common.Param() params: MedicamentoWhereUniqueInput
  ): Promise<Medicamento | null> {
    const result = await this.service.medicamento({
      where: params,
      select: {
        createdAt: true,
        dosis: true,
        id: true,
        nombre: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Medicamento })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Medicamento",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMedicamento(
    @common.Param() params: MedicamentoWhereUniqueInput,
    @common.Body() data: MedicamentoUpdateInput
  ): Promise<Medicamento | null> {
    try {
      return await this.service.updateMedicamento({
        where: params,
        data: data,
        select: {
          createdAt: true,
          dosis: true,
          id: true,
          nombre: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Medicamento })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Medicamento",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMedicamento(
    @common.Param() params: MedicamentoWhereUniqueInput
  ): Promise<Medicamento | null> {
    try {
      return await this.service.deleteMedicamento({
        where: params,
        select: {
          createdAt: true,
          dosis: true,
          id: true,
          nombre: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
