/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Medicamento as PrismaMedicamento } from "@prisma/client";

export class MedicamentoServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.MedicamentoCountArgs, "select">
  ): Promise<number> {
    return this.prisma.medicamento.count(args);
  }

  async medicamentos(
    args: Prisma.MedicamentoFindManyArgs
  ): Promise<PrismaMedicamento[]> {
    return this.prisma.medicamento.findMany(args);
  }
  async medicamento(
    args: Prisma.MedicamentoFindUniqueArgs
  ): Promise<PrismaMedicamento | null> {
    return this.prisma.medicamento.findUnique(args);
  }
  async createMedicamento(
    args: Prisma.MedicamentoCreateArgs
  ): Promise<PrismaMedicamento> {
    return this.prisma.medicamento.create(args);
  }
  async updateMedicamento(
    args: Prisma.MedicamentoUpdateArgs
  ): Promise<PrismaMedicamento> {
    return this.prisma.medicamento.update(args);
  }
  async deleteMedicamento(
    args: Prisma.MedicamentoDeleteArgs
  ): Promise<PrismaMedicamento> {
    return this.prisma.medicamento.delete(args);
  }
}
