/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Medicamento } from "./Medicamento";
import { MedicamentoCountArgs } from "./MedicamentoCountArgs";
import { MedicamentoFindManyArgs } from "./MedicamentoFindManyArgs";
import { MedicamentoFindUniqueArgs } from "./MedicamentoFindUniqueArgs";
import { CreateMedicamentoArgs } from "./CreateMedicamentoArgs";
import { UpdateMedicamentoArgs } from "./UpdateMedicamentoArgs";
import { DeleteMedicamentoArgs } from "./DeleteMedicamentoArgs";
import { MedicamentoService } from "../medicamento.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Medicamento)
export class MedicamentoResolverBase {
  constructor(
    protected readonly service: MedicamentoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Medicamento",
    action: "read",
    possession: "any",
  })
  async _medicamentosMeta(
    @graphql.Args() args: MedicamentoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Medicamento])
  @nestAccessControl.UseRoles({
    resource: "Medicamento",
    action: "read",
    possession: "any",
  })
  async medicamentos(
    @graphql.Args() args: MedicamentoFindManyArgs
  ): Promise<Medicamento[]> {
    return this.service.medicamentos(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Medicamento, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Medicamento",
    action: "read",
    possession: "own",
  })
  async medicamento(
    @graphql.Args() args: MedicamentoFindUniqueArgs
  ): Promise<Medicamento | null> {
    const result = await this.service.medicamento(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Medicamento)
  @nestAccessControl.UseRoles({
    resource: "Medicamento",
    action: "create",
    possession: "any",
  })
  async createMedicamento(
    @graphql.Args() args: CreateMedicamentoArgs
  ): Promise<Medicamento> {
    return await this.service.createMedicamento({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Medicamento)
  @nestAccessControl.UseRoles({
    resource: "Medicamento",
    action: "update",
    possession: "any",
  })
  async updateMedicamento(
    @graphql.Args() args: UpdateMedicamentoArgs
  ): Promise<Medicamento | null> {
    try {
      return await this.service.updateMedicamento({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Medicamento)
  @nestAccessControl.UseRoles({
    resource: "Medicamento",
    action: "delete",
    possession: "any",
  })
  async deleteMedicamento(
    @graphql.Args() args: DeleteMedicamentoArgs
  ): Promise<Medicamento | null> {
    try {
      return await this.service.deleteMedicamento(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
